---
- name: Install and configure tomcat
  hosts: linux
  become: true
  gather_facts: false
  vars: 
    req_java : java-11-amazon-corretto-devel
    java_path: jre-11-openjdk
    req_tomcat_ver: 10.1.9
    tomcat_port: 8090
  roles:
    - install-tomcat
